apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deployment
spec:
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: identity-serviceaccount
      containers:
      - name: identity
        image: playeconomyaxsg1.azurecr.io/play.identity:1.0.12
        env:
        - name: ServiceSettings__MessageBroker
          value: SERVICEBUS
        - name: ServiceSettings__KeyVaultName
          value: playeconomyaxsg1
        - name: IdentitySettings__PathBase
          value: /identity-svc/
        - name: IdentitySettings__CertificateCerFilePath
          value: "/certificates/certificate.crt"
        - name: IdentitySettings__CertificateKeyFilePath
          value: "/certificates/certificate.key"
        - name: IdentitySettings__Clients__0__RedirectUris__0
          value: "https://playeconomyaxsg1.eastus.cloudapp.azure.com/authentication/login-callback"
        - name: IdentitySettings__Clients__0__PostLogoutRedirectUris__0
          value: "https://playeconomyaxsg1.eastus.cloudapp.azure.com/authentication/logout-callback"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
        - containerPort: 5002
        livenessProbe:
          httpGet:
            path: /health/live
            port: 5002
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 5002
          initialDelaySeconds: 30
        volumeMounts:
          - name: certificate-volume
            mountPath: /certificates
            readOnly: true
      volumes:
        - name: certificate-volume
          secret:
            secretName: axsg1-signing-cert
            items:
              - key: tls.key
                path: certificate.key
              - key: tls.crt
                path: certificate.crt

---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  type: ClusterIP
  selector:
    app: identity
  ports:
  - port: 80
    targetPort: 5002

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: identity-serviceaccount
  annotations:
    azure.workload.identity/client-id: d1984c8c-6add-4c03-b658-57522698dc38
  labels:
    azure.workload.identity/use: "true"
