apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: axsg1-signing-cert
spec:
  secretName: axsg1-signing-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - playeconomyaxsg1.eastus.cloudapp.azure.com
  privateKey:
    rotationPolicy: Never